// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnchorCitation
 *
 * A `<cite>` span the substring validator resolved against a paper's
 * parsed text (D24) — `anchor_id` is a `quote_anchors` row, fetched via
 * `GET /api/anchors/:id` to drive `scroll_to` + `highlight_span` in the
 * reader (Phase 6.1).
 */
export type AnchorCitation = {
    /**
     * Kind
     */
    kind?: 'anchor';
    /**
     * Anchor Id
     */
    anchor_id: string;
    /**
     * Quote
     */
    quote: string;
};

/**
 * AnchorHint
 *
 * A cached rendering hint only — never identity (TRD §4.1).
 */
export type AnchorHint = {
    /**
     * Page
     */
    page: number;
    /**
     * Bbox
     */
    bbox: [
        number,
        number,
        number,
        number
    ];
};

/**
 * AssetInserted
 *
 * What inserting an image, a rendered Mermaid diagram, or a workspace
 * dataviz export into a manuscript returns — the vault-relative path the
 * editor inlines into an `\includegraphics{...}` snippet.
 */
export type AssetInserted = {
    /**
     * Path
     */
    path: string;
};

/**
 * Body_insert_asset_api_projects__project_id__documents__document_id__assets_post
 */
export type BodyInsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CheckCitationsResponse
 */
export type CheckCitationsResponse = {
    /**
     * Findings
     */
    findings: Array<CitationFinding>;
};

/**
 * CitationFinding
 *
 * One entry of `documents.citation_findings` (Schema.md) — a missing
 * `\cite` target or a claim `check_citations` could not link to a source.
 */
export type CitationFinding = {
    /**
     * Kind
     */
    kind: 'missing' | 'unsupported';
    /**
     * Span
     */
    span: string;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * CitedRow
 *
 * One retrieval hit, always traceable back to the row it came from
 * (MODULES.md `query_memory`) — the paper it's from when it has one, the
 * verbatim text, and the span within the source artifact.
 */
export type CitedRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Source Type
     */
    source_type: 'paper_section' | 'abstract' | 'note' | 'experiment' | 'conversation_summary';
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Paper Id
     */
    paper_id: string | null;
    /**
     * Text
     */
    text: string;
    /**
     * Section Heading
     */
    section_heading: string | null;
    /**
     * Char Start
     */
    char_start: number;
    /**
     * Char End
     */
    char_end: number;
};

/**
 * ColumnDef
 */
export type ColumnDef = {
    /**
     * Column Key
     */
    column_key: string;
    /**
     * Label
     */
    label: string;
    /**
     * Kind
     */
    kind: 'standard' | 'custom' | 'user';
    /**
     * Query
     */
    query?: string | null;
};

/**
 * CompileResult
 *
 * What a Tectonic compile returns — success or failure, never a 500
 * (MODULES.md's Errors clause). On failure the previous `.tex` on disk is
 * untouched, so `document` is the unchanged prior row.
 */
export type CompileResult = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Engine
     */
    engine: 'tectonic';
    /**
     * Log
     */
    log: string;
    document: Document;
};

/**
 * ConfirmationToken
 *
 * The one-shot credential `run_all` requires (D31) — opaque beyond the
 * fields the approval prompt needs to display (`expires_at`, for a
 * countdown or a "this approval expired, review again" message).
 */
export type ConfirmationToken = {
    /**
     * Token
     */
    token: string;
    /**
     * Experiment Id
     */
    experiment_id: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * ConversationResponse
 */
export type ConversationResponse = {
    /**
     * Messages
     */
    messages: Array<MessageOut>;
};

/**
 * CreateProjectRequest
 */
export type CreateProjectRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Focus Seed
     */
    focus_seed?: string | null;
};

/**
 * DashboardStat
 *
 * One stat-row tile (UI_DESIGN.md §4.1): `total` is the tile's big
 * number, `qualifier` is the always-actionable-subset phrase rendered
 * under it (`"4 unmarked"`, `"1 in progress"`, `"new since Tue"`) — never
 * a bare count on its own.
 */
export type DashboardStat = {
    /**
     * Total
     */
    total: number;
    /**
     * Qualifier
     */
    qualifier: string;
};

/**
 * DashboardSummary
 */
export type DashboardSummary = {
    papers: DashboardStat;
    notes: DashboardStat;
    experiments: DashboardStat;
    feed: DashboardStat;
    /**
     * Needs Attention
     */
    needs_attention: Array<NeedsAttentionItem>;
};

/**
 * DiscoverModelsRequest
 */
export type DiscoverModelsRequest = {
    /**
     * Provider
     */
    provider: 'ollama' | 'vllm';
    /**
     * Base Url
     */
    base_url: string;
};

/**
 * DiscoverModelsResponse
 */
export type DiscoverModelsResponse = {
    /**
     * Models
     */
    models: Array<string>;
};

/**
 * Document
 *
 * The `documents` row (Schema.md), returned by every writing endpoint.
 */
export type Document = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Body
     */
    body: string;
    /**
     * Citation Findings
     */
    citation_findings: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Last Compiled At
     */
    last_compiled_at: string | null;
    /**
     * Last Compile Engine
     */
    last_compile_engine: 'swiftlatex' | 'tectonic' | null;
};

/**
 * Experiment
 *
 * The `experiments` row (Schema.md), returned by every experiments endpoint.
 */
export type Experiment = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Hypothesis
     */
    hypothesis: string | null;
    /**
     * Setup
     */
    setup: {
        [key: string]: unknown;
    };
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Status
     */
    status: 'planned' | 'remaining' | 'in-progress' | 'done';
    /**
     * Notebook Path
     */
    notebook_path: string | null;
    /**
     * Network Optin
     */
    network_optin: boolean;
    /**
     * Gpu Optin
     */
    gpu_optin: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ExperimentInput
 *
 * What a caller submits to create or update an experiment record.
 *
 * All fields are optional so `update_experiment` can patch just one; on
 * create, `title` is the only one that must be present in practice — the
 * module enforces that, not this shape.
 */
export type ExperimentInput = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Hypothesis
     */
    hypothesis?: string | null;
    /**
     * Setup
     */
    setup?: {
        [key: string]: unknown;
    } | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Status
     */
    status?: 'planned' | 'remaining' | 'in-progress' | 'done' | null;
    /**
     * Network Optin
     */
    network_optin?: boolean | null;
    /**
     * Gpu Optin
     */
    gpu_optin?: boolean | null;
};

/**
 * ExperimentMetric
 *
 * The `experiment_metrics` row (Schema.md), returned by the metrics endpoint.
 */
export type ExperimentMetric = {
    /**
     * Id
     */
    id: string;
    /**
     * Experiment Id
     */
    experiment_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Value
     */
    value: string;
    /**
     * Unit
     */
    unit: string | null;
    /**
     * Source
     */
    source: 'user' | 'measured';
    /**
     * Run Id
     */
    run_id: string | null;
    /**
     * Recorded At
     */
    recorded_at: string;
};

/**
 * ExperimentRun
 *
 * The `experiment_runs` row (Schema.md) — the strongest provenance in
 * the system. `approved_at` is always set: a row cannot exist without a
 * validated confirmation token (D31, invariant #5). This is the type
 * `record_run` returns and `is_measured_eligible` inspects; Execution
 * Sandbox re-exports it (`sandbox.models.ExperimentRun`) rather than
 * defining a second, duplicate shape, since Experiment Record is the
 * module that persists this row (MODULES.md's own `record_run` signature).
 */
export type ExperimentRun = {
    /**
     * Id
     */
    id: string;
    /**
     * Experiment Id
     */
    experiment_id: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Exit Code
     */
    exit_code: number | null;
    /**
     * Image
     */
    image: string;
    /**
     * Reqs Hash
     */
    reqs_hash: string;
    /**
     * Notebook Hash
     */
    notebook_hash: string;
    /**
     * Stdout Ref
     */
    stdout_ref: string;
    /**
     * Artifacts
     */
    artifacts: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Run Kind
     */
    run_kind: 'clean_run_all' | 'interactive';
    /**
     * Network Enabled
     */
    network_enabled: boolean;
    /**
     * Gpu Enabled
     */
    gpu_enabled: boolean;
    /**
     * Approved At
     */
    approved_at: string;
};

/**
 * FeedActionRequest
 */
export type FeedActionRequest = {
    /**
     * Action
     */
    action: 'save' | 'dismiss';
    /**
     * Item Id
     */
    item_id: string;
};

/**
 * FeedItem
 */
export type FeedItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Canonical Id
     */
    canonical_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Score
     */
    score: number;
    why_relevant: WhyRelevant;
    /**
     * State
     */
    state: 'new' | 'saved' | 'dismissed';
    /**
     * Polled At
     */
    polled_at: string;
};

/**
 * Graph
 */
export type Graph = {
    /**
     * Edges
     */
    edges: Array<GraphEdge>;
    /**
     * Paper Ids
     */
    paper_ids?: {
        [key: string]: string;
    };
    /**
     * Paper Titles
     */
    paper_titles?: {
        [key: string]: string;
    };
};

/**
 * GraphEdge
 */
export type GraphEdge = {
    /**
     * Id
     */
    id: string;
    /**
     * Src Type
     */
    src_type: 'paper' | 'author' | 'dataset' | 'repo' | 'topic' | 'method' | 'concept' | 'note' | 'experiment' | 'highlight';
    /**
     * Src Id
     */
    src_id: string;
    /**
     * Dst Type
     */
    dst_type: 'paper' | 'author' | 'dataset' | 'repo' | 'topic' | 'method' | 'concept' | 'note' | 'experiment' | 'highlight';
    /**
     * Dst Id
     */
    dst_id: string;
    /**
     * Relation
     */
    relation: 'cites' | 'cited_by' | 'authored_by' | 'uses_dataset' | 'has_code' | 'has_topic' | 'method_of' | 'related_method' | 'inspired_by' | 'references_note' | 'relates_to' | 'contradicts';
    /**
     * Provenance
     */
    provenance: 'metadata' | 'llm' | 'user';
    /**
     * Confidence
     */
    confidence?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Capabilities
     */
    capabilities: {
        [key: string]: 'pending' | 'ready' | 'failed';
    };
};

/**
 * Highlight
 *
 * The `highlights` row (Schema.md), returned by the highlights endpoint.
 */
export type Highlight = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Paper Id
     */
    paper_id: string;
    /**
     * Anchor Id
     */
    anchor_id: string;
    /**
     * Quote
     */
    quote: string;
    /**
     * Char Start
     */
    char_start: number;
    /**
     * Char End
     */
    char_end: number;
    /**
     * Section Heading
     */
    section_heading: string | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Color
     */
    color: string | null;
    /**
     * Note Id
     */
    note_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HighlightInput
 *
 * `POST /api/projects/:id/highlights` request body (TRD §4.2).
 */
export type HighlightInput = {
    /**
     * Paper Id
     */
    paper_id: string;
    anchor: QuoteAnchorInput;
    /**
     * Comment
     */
    comment?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Note Id
     */
    note_id?: string | null;
};

/**
 * InterestProfile
 *
 * Inspectable and user-editable (D28) — the fetch's category window and
 * the ranking's keyword-match term are both read from exactly this.
 */
export type InterestProfile = {
    /**
     * Categories
     */
    categories?: Array<string>;
    /**
     * Keywords
     */
    keywords?: Array<string>;
};

/**
 * KernelActionRequest
 */
export type KernelActionRequest = {
    /**
     * Action
     */
    action: 'start' | 'stop';
};

/**
 * KernelStatus
 *
 * Response for `POST /api/experiments/:id/kernel`. Under the `nbclient`
 * fallback (D30's descope) there is no persistent per-experiment kernel to
 * start or stop — containers are per-run, not per-experiment. `state`
 * honestly reports the only kernel-shaped fact that exists here: whether
 * this experiment currently has an in-flight run container. `"start"`
 * cannot create anything real to report back beyond this same status;
 * `"stop"` maps to cancelling that in-flight container, if any.
 */
export type KernelStatus = {
    /**
     * Experiment Id
     */
    experiment_id: string;
    /**
     * State
     */
    state: 'idle' | 'running';
    /**
     * Run Id
     */
    run_id?: string | null;
};

/**
 * LibraryEntry
 */
export type LibraryEntry = {
    paper: Paper;
    /**
     * Relevance
     */
    relevance: string;
    /**
     * Why Relevant
     */
    why_relevant: string | null;
};

/**
 * Matrix
 */
export type Matrix = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Selected Paper Ids
     */
    selected_paper_ids: Array<string>;
    /**
     * Selected Experiment Ids
     */
    selected_experiment_ids: Array<string>;
    /**
     * Column Defs
     */
    column_defs: Array<ColumnDef>;
};

/**
 * MatrixCell
 */
export type MatrixCell = {
    /**
     * Row Id
     */
    row_id: string;
    /**
     * Row Kind
     */
    row_kind: 'paper' | 'experiment';
    /**
     * Column Key
     */
    column_key: string;
    /**
     * Value
     */
    value: string;
    /**
     * Source
     */
    source: 'extracted' | 'user';
    /**
     * Anchor Id
     */
    anchor_id?: string | null;
    /**
     * Section Heading
     */
    section_heading?: string | null;
    /**
     * Char Start
     */
    char_start?: number | null;
    /**
     * Char End
     */
    char_end?: number | null;
};

/**
 * MatrixRow
 */
export type MatrixRow = {
    /**
     * Row Id
     */
    row_id: string;
    /**
     * Row Kind
     */
    row_kind: 'paper' | 'experiment';
    /**
     * Label
     */
    label: string;
};

/**
 * MatrixUpdate
 *
 * What a caller submits to `update_matrix` — one `PUT`-shaped write
 * (MODULES.md); every field optional so a partial update only touches
 * what it names.
 */
export type MatrixUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Selected Paper Ids
     */
    selected_paper_ids?: Array<string> | null;
    /**
     * Selected Experiment Ids
     */
    selected_experiment_ids?: Array<string> | null;
    /**
     * Column Defs
     */
    column_defs?: Array<ColumnDef> | null;
};

/**
 * MatrixView
 */
export type MatrixView = {
    matrix: Matrix;
    /**
     * Rows
     */
    rows: Array<MatrixRow>;
    /**
     * Cells
     */
    cells: Array<MatrixCell>;
};

/**
 * MemoryCitation
 *
 * A `<cite>` span resolved against a `query_memory` row instead of a
 * live paper anchor — no reader position to scroll to, so this kind is
 * rendered but not clickable.
 */
export type MemoryCitation = {
    /**
     * Kind
     */
    kind?: 'memory';
    /**
     * Row Id
     */
    row_id: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Quote
     */
    quote: string;
};

/**
 * MemoryQueryRequest
 */
export type MemoryQueryRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Types
     */
    types?: Array<string> | null;
};

/**
 * MemoryQueryResponse
 */
export type MemoryQueryResponse = {
    /**
     * Rows
     */
    rows: Array<CitedRow>;
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Citations
     */
    citations: Array<AnchorCitation | MemoryCitation>;
    /**
     * Interrupted
     */
    interrupted: boolean;
    /**
     * Input Modality
     */
    input_modality: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MetricInput
 *
 * What a caller submits to `record_metric`. `source: llm` is
 * unrepresentable at the type level (`MetricSource`); `run_id` is required
 * by the caller only when `source='measured'` — the DB `CHECK` is what
 * actually enforces that pairing (MODULES.md), this shape just allows it.
 */
export type MetricInput = {
    /**
     * Name
     */
    name: string;
    /**
     * Value
     */
    value: string;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Source
     */
    source: 'user' | 'measured';
    /**
     * Run Id
     */
    run_id?: string | null;
};

/**
 * ModelSettings
 */
export type ModelSettings = {
    /**
     * Providers
     */
    providers: {
        [key: string]: ProviderInfo;
    };
    /**
     * Primary Model
     */
    primary_model?: string | null;
    /**
     * Auxiliary Model
     */
    auxiliary_model?: string | null;
    /**
     * Onboarding Completed At
     */
    onboarding_completed_at?: string | null;
};

/**
 * MountSpec
 *
 * One bind mount into the run container (D30/Rules.md: never the whole
 * vault, never `$HOME`).
 */
export type MountSpec = {
    /**
     * Host Path
     */
    host_path: string;
    /**
     * Container Path
     */
    container_path: string;
    /**
     * Mode
     */
    mode: 'ro' | 'rw';
};

/**
 * NeedsAttentionItem
 *
 * One row of the `NEEDS ATTENTION` stack, mixing two severities on
 * purpose (UI_DESIGN.md §4.1): `nudge` renders as the dashed soft-prompt
 * block (§3.4), `error` as the danger error card. `paper_id` is present
 * only on a `retry`-actionable error, so the frontend can call the
 * existing Phase 1.3 reprocess endpoint directly from this row.
 */
export type NeedsAttentionItem = {
    /**
     * Severity
     */
    severity: 'nudge' | 'error';
    /**
     * Message
     */
    message: string;
    /**
     * Paper Id
     */
    paper_id?: string | null;
    /**
     * Action
     */
    action?: 'retry' | null;
};

/**
 * Note
 *
 * The `notes` row (Schema.md), returned by every notes endpoint.
 */
export type Note = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Body
     */
    body: string;
    /**
     * Frontmatter
     */
    frontmatter: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * NoteInput
 *
 * What a caller submits to create or update a note.
 *
 * `frontmatter_id` is absent to create (Vault Writer assigns one) and
 * present to update — the id carried in the note's own YAML frontmatter,
 * never the file path (D4).
 */
export type NoteInput = {
    /**
     * Frontmatter Id
     */
    frontmatter_id?: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
};

/**
 * Notebook
 *
 * The vault notebook's cell list, returned by `propose_cell`.
 */
export type Notebook = {
    /**
     * Experiment Id
     */
    experiment_id: string;
    /**
     * Cells
     */
    cells: Array<NotebookCell>;
};

/**
 * NotebookCell
 *
 * One cell as the UI needs to render it. `execution_count` and
 * `outputs` absent/empty is the unrun signal `propose_cell` relies on —
 * nbformat's own freshly-created code cell already carries no other kind
 * of "pending approval" marker, so none is invented here (MODULES.md).
 */
export type NotebookCell = {
    /**
     * Cell Type
     */
    cell_type: 'code' | 'markdown' | 'raw';
    /**
     * Source
     */
    source: string;
    /**
     * Execution Count
     */
    execution_count?: number | null;
    /**
     * Outputs
     */
    outputs?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * NotebookServerAction
 *
 * Request body for `POST /api/experiments/:id/notebook_server`.
 */
export type NotebookServerAction = {
    /**
     * Action
     */
    action: 'start' | 'stop';
};

/**
 * NotebookServerStatus
 *
 * Response for the live-notebook-server route (Phase 2.4). A
 * deliberately separate model family from `KernelStatus`: that type's
 * whole point is to honestly describe the one-shot measured path, where
 * there is nothing persistent to start — conflating the two would make one
 * type lie about whichever path didn't populate it. `url` is `None` unless
 * `state == "running"`.
 */
export type NotebookServerStatus = {
    /**
     * Experiment Id
     */
    experiment_id: string;
    /**
     * State
     */
    state: 'stopped' | 'starting' | 'running' | 'stopping';
    /**
     * Url
     */
    url?: string | null;
    /**
     * Port
     */
    port?: number | null;
    /**
     * Network
     */
    network?: 'bridge' | 'internal' | null;
    /**
     * Started At
     */
    started_at?: string | null;
};

/**
 * Paper
 */
export type Paper = {
    /**
     * Id
     */
    id: string;
    /**
     * Canonical Id
     */
    canonical_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Abstract
     */
    abstract?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Pdf Origin
     */
    pdf_origin?: string | null;
    /**
     * Fetch State
     */
    fetch_state: string;
    /**
     * Parse State
     */
    parse_state: string;
    /**
     * Embed State
     */
    embed_state: string;
    /**
     * Extract State
     */
    extract_state: string;
};

/**
 * PaperCardField
 */
export type PaperCardField = {
    /**
     * Field Key
     */
    field_key: string;
    /**
     * Value
     */
    value: string;
    /**
     * Anchor Id
     */
    anchor_id: string;
    /**
     * Section Heading
     */
    section_heading?: string | null;
    /**
     * Char Start
     */
    char_start: number;
    /**
     * Char End
     */
    char_end: number;
};

/**
 * PaperContentView
 */
export type PaperContentView = {
    /**
     * Full Text
     */
    full_text: string;
    /**
     * Sections
     */
    sections: Array<SectionInfo>;
    /**
     * References
     */
    references: Array<ReferenceInfo>;
    /**
     * Datasets
     */
    datasets: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Code Links
     */
    code_links: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Parsed At
     */
    parsed_at: string;
};

/**
 * PaperDetail
 */
export type PaperDetail = {
    paper: Paper;
    content?: PaperContentView | null;
    /**
     * Card
     */
    card?: Array<PaperCardField> | null;
};

/**
 * PaperInput
 *
 * What the caller submits to add a paper — from a search result or a
 * pasted link/id. A pure upload with no resolvable id is out of scope for
 * v1: `canonical_id_source` (Schema.md) has no "upload" value, so at least
 * one of doi/arxiv_id/openalex_id/s2_id is required.
 */
export type PaperInput = {
    source_ids: SourceIds;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Abstract
     */
    abstract?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Pdf Url
     */
    pdf_url?: string | null;
};

/**
 * PaperSummary
 */
export type PaperSummary = {
    /**
     * Canonical Id
     */
    canonical_id: string;
    source_ids: SourceIds;
    /**
     * Title
     */
    title: string;
    /**
     * Abstract
     */
    abstract?: string | null;
    /**
     * Authors
     */
    authors?: Array<string>;
    /**
     * Year
     */
    year?: number | null;
    /**
     * Venue
     */
    venue?: string | null;
    /**
     * Citation Count
     */
    citation_count?: number | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Pdf Url
     */
    pdf_url?: string | null;
};

/**
 * PatchProjectPaperRequest
 */
export type PatchProjectPaperRequest = {
    /**
     * Relevance
     */
    relevance?: 'relevant' | 'somewhat' | 'not' | 'unset' | null;
    /**
     * Why Relevant
     */
    why_relevant?: string | null;
};

/**
 * ProjectPaperResponse
 */
export type ProjectPaperResponse = {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Paper Id
     */
    paper_id: string;
    /**
     * Relevance
     */
    relevance: string;
    /**
     * Why Relevant
     */
    why_relevant: string | null;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Focus Seed
     */
    focus_seed: string | null;
    /**
     * Last Opened At
     */
    last_opened_at: string | null;
    /**
     * Tab Stack
     */
    tab_stack: Array<TabRef>;
    /**
     * Active Tab
     */
    active_tab: string | null;
};

/**
 * ProposeCellRequest
 */
export type ProposeCellRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Index
     */
    index?: number | null;
};

/**
 * ProviderCredentials
 *
 * What the user submits to save and validate one provider.
 */
export type ProviderCredentials = {
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Tier
     */
    tier?: 'primary' | 'auxiliary';
    /**
     * Model Budgets
     */
    model_budgets?: {
        [key: string]: number;
    };
};

/**
 * ProviderInfo
 *
 * What is ever read back — never ciphertext, nonce, or plaintext key.
 */
export type ProviderInfo = {
    /**
     * Last4
     */
    last4?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Validated At
     */
    validated_at?: string | null;
    /**
     * Model Budgets
     */
    model_budgets?: {
        [key: string]: number;
    };
};

/**
 * QuoteAnchor
 *
 * The shared quote-anchor object (D33) — one shape for a card field, a
 * highlight, a matrix cell and a Companion citation.
 */
export type QuoteAnchor = {
    /**
     * Id
     */
    id: string;
    /**
     * Paper Id
     */
    paper_id: string;
    /**
     * Quote
     */
    quote: string;
    /**
     * Prefix
     */
    prefix: string;
    /**
     * Suffix
     */
    suffix: string;
    /**
     * Char Start
     */
    char_start: number;
    /**
     * Char End
     */
    char_end: number;
    /**
     * Section Heading
     */
    section_heading?: string | null;
    /**
     * Page Hint
     */
    page_hint?: number | null;
    /**
     * Validated At
     */
    validated_at: string;
};

/**
 * QuoteAnchorInput
 *
 * The wire shape of `QuoteAnchor` in TRD §4.1 — what a caller submits
 * to be validated and anchored fresh (D24), same as an extractive card
 * field.
 */
export type QuoteAnchorInput = {
    /**
     * Quote
     */
    quote: string;
    /**
     * Prefix
     */
    prefix: string;
    /**
     * Suffix
     */
    suffix: string;
    hint?: AnchorHint | null;
};

/**
 * Reference
 *
 * One of the project's own papers, shaped for `\cite` autocomplete and
 * BibTeX export — `cite_key` is the same deterministic value both surfaces
 * use, so a key inserted while autocompleting always resolves in the
 * exported `.bib`.
 */
export type Reference = {
    /**
     * Paper Id
     */
    paper_id: string;
    /**
     * Cite Key
     */
    cite_key: string;
    /**
     * Title
     */
    title: string;
    /**
     * Authors
     */
    authors?: Array<string>;
    /**
     * Year
     */
    year?: number | null;
};

/**
 * ReferenceInfo
 */
export type ReferenceInfo = {
    /**
     * Ref Id
     */
    ref_id: string;
    /**
     * Raw
     */
    raw: string;
};

/**
 * ResultSet
 */
export type ResultSet = {
    /**
     * Result Id
     */
    result_id: string;
    /**
     * Query
     */
    query: string;
    /**
     * Results
     */
    results: Array<PaperSummary>;
    /**
     * Sources Failed
     */
    sources_failed?: Array<string>;
};

/**
 * RunAllRequest
 */
export type RunAllRequest = {
    /**
     * Confirmation Token
     */
    confirmation_token: string;
    /**
     * Network Optin
     */
    network_optin?: boolean;
    /**
     * Gpu
     */
    gpu?: boolean;
};

/**
 * RunAllResponse
 */
export type RunAllResponse = {
    /**
     * Run Id
     */
    run_id: string;
};

/**
 * RunDetail
 *
 * `ExperimentRun` plus the run's captured stdout log content — the log
 * itself lives on disk (`stdout_ref` is a vault-relative path), so this
 * reads it back rather than making the caller resolve the path itself.
 */
export type RunDetail = {
    run: ExperimentRun;
    /**
     * Stdout
     */
    stdout: string;
};

/**
 * RunSpec
 *
 * The container spec the approval prompt displays before `run_all` can
 * mint a confirmation (D31) — image, mounts, network, and the limits that
 * are "always set" per Rules.md's Security Rules. Nothing in Phase 2.1
 * consumes this yet; `mint_confirmation`/`run_all` (Phase 2.2) do.
 */
export type RunSpec = {
    /**
     * Image
     */
    image: string;
    /**
     * Mounts
     */
    mounts: Array<MountSpec>;
    /**
     * Network
     */
    network?: 'none' | 'bridge';
    /**
     * Cpu Limit
     */
    cpu_limit: number;
    /**
     * Memory Limit Mb
     */
    memory_limit_mb: number;
    /**
     * Idle Timeout Seconds
     */
    idle_timeout_seconds: number;
    /**
     * Cell Timeout Seconds
     */
    cell_timeout_seconds: number;
    /**
     * Gpu
     */
    gpu?: boolean;
};

/**
 * RunSpecPreview
 *
 * What the approval prompt renders before a human confirms: the
 * proposed code and the full container spec (image, mounts, network,
 * GPU) — D31's explicit requirement for what the prompt must show.
 */
export type RunSpecPreview = {
    notebook: Notebook;
    run_spec: RunSpec;
};

/**
 * SaveDocumentRequest
 */
export type SaveDocumentRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Tex
     */
    tex: string;
    /**
     * Engine
     */
    engine?: 'swiftlatex' | 'tectonic' | null;
};

/**
 * SaveModelBudgetRequest
 */
export type SaveModelBudgetRequest = {
    /**
     * Provider
     */
    provider: 'google' | 'groq' | 'openai' | 'anthropic' | 'openrouter' | 'deepseek' | 'custom' | 'ollama' | 'vllm';
    /**
     * Model
     */
    model: string;
    /**
     * Budget
     */
    budget: number;
};

/**
 * SaveProviderRequest
 */
export type SaveProviderRequest = {
    /**
     * Provider
     */
    provider: 'google' | 'groq' | 'openai' | 'anthropic' | 'openrouter' | 'deepseek' | 'custom' | 'ollama' | 'vllm';
    credentials: ProviderCredentials;
};

/**
 * SaveTabStackRequest
 */
export type SaveTabStackRequest = {
    /**
     * Tab Stack
     */
    tab_stack: Array<TabRef>;
    /**
     * Active Tab
     */
    active_tab?: string | null;
};

/**
 * SearchFilters
 */
export type SearchFilters = {
    /**
     * Year Min
     */
    year_min?: number | null;
    /**
     * Year Max
     */
    year_max?: number | null;
    /**
     * Venue
     */
    venue?: string | null;
    /**
     * Has Code
     */
    has_code?: boolean | null;
    /**
     * Author
     */
    author?: string | null;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
    filters?: SearchFilters | null;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * SectionInfo
 */
export type SectionInfo = {
    /**
     * Section Id
     */
    section_id: string;
    /**
     * Heading
     */
    heading: string;
    /**
     * Level
     */
    level: number;
    /**
     * Char Start
     */
    char_start: number;
    /**
     * Char End
     */
    char_end: number;
};

/**
 * SourceIds
 *
 * Whatever source ids a literature API returned for one paper.
 */
export type SourceIds = {
    /**
     * Doi
     */
    doi?: string | null;
    /**
     * Arxiv Id
     */
    arxiv_id?: string | null;
    /**
     * Openalex Id
     */
    openalex_id?: string | null;
    /**
     * S2 Id
     */
    s2_id?: string | null;
};

/**
 * SynthesizeRequest
 */
export type SynthesizeRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Voice
     */
    voice?: string;
};

/**
 * TabRef
 *
 * One entry in the persisted center-pane tab stack (TRD §4.1's
 * `TabRef`) — a routed view instance, e.g. two open papers are two
 * entries with the same `kind` and different `params`.
 */
export type TabRef = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Params
     */
    params?: {
        [key: string]: string;
    };
    /**
     * Label
     */
    label: string;
};

/**
 * Transcript
 */
export type Transcript = {
    /**
     * Text
     */
    text: string;
};

/**
 * UpdateCellRequest
 */
export type UpdateCellRequest = {
    /**
     * Row Id
     */
    row_id: string;
    /**
     * Column Key
     */
    column_key: string;
    /**
     * Value
     */
    value: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VaultPathRequest
 */
export type VaultPathRequest = {
    /**
     * Path
     */
    path: string;
};

/**
 * WhyRelevant
 *
 * Why one item surfaced. Required on every `FeedItem` — an item with
 * none of these non-empty never reaches `feed_items` (Rules.md).
 */
export type WhyRelevant = {
    /**
     * Matched Keywords
     */
    matched_keywords?: Array<string>;
    /**
     * Matched Categories
     */
    matched_categories?: Array<string>;
    /**
     * Similarity
     */
    similarity?: number;
};

export type GetHealthApiHealthGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthApiHealthGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHealthApiHealthGetError = GetHealthApiHealthGetErrors[keyof GetHealthApiHealthGetErrors];

export type GetHealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthApiHealthGetResponse = GetHealthApiHealthGetResponses[keyof GetHealthApiHealthGetResponses];

export type GetModelsApiSettingsModelsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/models';
};

export type GetModelsApiSettingsModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelsApiSettingsModelsGetError = GetModelsApiSettingsModelsGetErrors[keyof GetModelsApiSettingsModelsGetErrors];

export type GetModelsApiSettingsModelsGetResponses = {
    /**
     * Successful Response
     */
    200: ModelSettings;
};

export type GetModelsApiSettingsModelsGetResponse = GetModelsApiSettingsModelsGetResponses[keyof GetModelsApiSettingsModelsGetResponses];

export type PutModelsApiSettingsModelsPutData = {
    body: SaveProviderRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/models';
};

export type PutModelsApiSettingsModelsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutModelsApiSettingsModelsPutError = PutModelsApiSettingsModelsPutErrors[keyof PutModelsApiSettingsModelsPutErrors];

export type PutModelsApiSettingsModelsPutResponses = {
    /**
     * Successful Response
     */
    200: ModelSettings;
};

export type PutModelsApiSettingsModelsPutResponse = PutModelsApiSettingsModelsPutResponses[keyof PutModelsApiSettingsModelsPutResponses];

export type PutModelBudgetApiSettingsModelsBudgetPutData = {
    body: SaveModelBudgetRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/models/budget';
};

export type PutModelBudgetApiSettingsModelsBudgetPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutModelBudgetApiSettingsModelsBudgetPutError = PutModelBudgetApiSettingsModelsBudgetPutErrors[keyof PutModelBudgetApiSettingsModelsBudgetPutErrors];

export type PutModelBudgetApiSettingsModelsBudgetPutResponses = {
    /**
     * Successful Response
     */
    200: ModelSettings;
};

export type PutModelBudgetApiSettingsModelsBudgetPutResponse = PutModelBudgetApiSettingsModelsBudgetPutResponses[keyof PutModelBudgetApiSettingsModelsBudgetPutResponses];

export type DiscoverModelsApiSettingsModelsDiscoverPostData = {
    body: DiscoverModelsRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/models/discover';
};

export type DiscoverModelsApiSettingsModelsDiscoverPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DiscoverModelsApiSettingsModelsDiscoverPostError = DiscoverModelsApiSettingsModelsDiscoverPostErrors[keyof DiscoverModelsApiSettingsModelsDiscoverPostErrors];

export type DiscoverModelsApiSettingsModelsDiscoverPostResponses = {
    /**
     * Successful Response
     */
    200: DiscoverModelsResponse;
};

export type DiscoverModelsApiSettingsModelsDiscoverPostResponse = DiscoverModelsApiSettingsModelsDiscoverPostResponses[keyof DiscoverModelsApiSettingsModelsDiscoverPostResponses];

export type PutVaultPathApiSettingsVaultPathPutData = {
    body: VaultPathRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/vault-path';
};

export type PutVaultPathApiSettingsVaultPathPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutVaultPathApiSettingsVaultPathPutError = PutVaultPathApiSettingsVaultPathPutErrors[keyof PutVaultPathApiSettingsVaultPathPutErrors];

export type PutVaultPathApiSettingsVaultPathPutResponses = {
    /**
     * Response Put Vault Path Api Settings Vault Path Put
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PutVaultPathApiSettingsVaultPathPutResponse = PutVaultPathApiSettingsVaultPathPutResponses[keyof PutVaultPathApiSettingsVaultPathPutResponses];

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/onboarding-complete';
};

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutError = PutOnboardingCompleteApiSettingsOnboardingCompletePutErrors[keyof PutOnboardingCompleteApiSettingsOnboardingCompletePutErrors];

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutResponses = {
    /**
     * Successful Response
     */
    200: ModelSettings;
};

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutResponse = PutOnboardingCompleteApiSettingsOnboardingCompletePutResponses[keyof PutOnboardingCompleteApiSettingsOnboardingCompletePutResponses];

export type ListProjectsApiProjectsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type ListProjectsApiProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsApiProjectsGetError = ListProjectsApiProjectsGetErrors[keyof ListProjectsApiProjectsGetErrors];

export type ListProjectsApiProjectsGetResponses = {
    /**
     * Response List Projects Api Projects Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type ListProjectsApiProjectsGetResponse = ListProjectsApiProjectsGetResponses[keyof ListProjectsApiProjectsGetResponses];

export type CreateProjectApiProjectsPostData = {
    body: CreateProjectRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type CreateProjectApiProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiProjectsPostError = CreateProjectApiProjectsPostErrors[keyof CreateProjectApiProjectsPostErrors];

export type CreateProjectApiProjectsPostResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type CreateProjectApiProjectsPostResponse = CreateProjectApiProjectsPostResponses[keyof CreateProjectApiProjectsPostResponses];

export type GetProjectApiProjectsProjectIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type GetProjectApiProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiProjectsProjectIdGetError = GetProjectApiProjectsProjectIdGetErrors[keyof GetProjectApiProjectsProjectIdGetErrors];

export type GetProjectApiProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectApiProjectsProjectIdGetResponse = GetProjectApiProjectsProjectIdGetResponses[keyof GetProjectApiProjectsProjectIdGetResponses];

export type GetDashboardApiProjectsProjectIdDashboardGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/dashboard';
};

export type GetDashboardApiProjectsProjectIdDashboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDashboardApiProjectsProjectIdDashboardGetError = GetDashboardApiProjectsProjectIdDashboardGetErrors[keyof GetDashboardApiProjectsProjectIdDashboardGetErrors];

export type GetDashboardApiProjectsProjectIdDashboardGetResponses = {
    /**
     * Successful Response
     */
    200: DashboardSummary;
};

export type GetDashboardApiProjectsProjectIdDashboardGetResponse = GetDashboardApiProjectsProjectIdDashboardGetResponses[keyof GetDashboardApiProjectsProjectIdDashboardGetResponses];

export type SaveTabStackApiProjectsProjectIdTabStackPutData = {
    body: SaveTabStackRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tab-stack';
};

export type SaveTabStackApiProjectsProjectIdTabStackPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveTabStackApiProjectsProjectIdTabStackPutError = SaveTabStackApiProjectsProjectIdTabStackPutErrors[keyof SaveTabStackApiProjectsProjectIdTabStackPutErrors];

export type SaveTabStackApiProjectsProjectIdTabStackPutResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type SaveTabStackApiProjectsProjectIdTabStackPutResponse = SaveTabStackApiProjectsProjectIdTabStackPutResponses[keyof SaveTabStackApiProjectsProjectIdTabStackPutResponses];

export type ListNotesApiProjectsProjectIdNotesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/notes';
};

export type ListNotesApiProjectsProjectIdNotesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListNotesApiProjectsProjectIdNotesGetError = ListNotesApiProjectsProjectIdNotesGetErrors[keyof ListNotesApiProjectsProjectIdNotesGetErrors];

export type ListNotesApiProjectsProjectIdNotesGetResponses = {
    /**
     * Response List Notes Api Projects  Project Id  Notes Get
     *
     * Successful Response
     */
    200: Array<Note>;
};

export type ListNotesApiProjectsProjectIdNotesGetResponse = ListNotesApiProjectsProjectIdNotesGetResponses[keyof ListNotesApiProjectsProjectIdNotesGetResponses];

export type UpdateNoteApiProjectsProjectIdNotesPatchData = {
    body: NoteInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/notes';
};

export type UpdateNoteApiProjectsProjectIdNotesPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNoteApiProjectsProjectIdNotesPatchError = UpdateNoteApiProjectsProjectIdNotesPatchErrors[keyof UpdateNoteApiProjectsProjectIdNotesPatchErrors];

export type UpdateNoteApiProjectsProjectIdNotesPatchResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type UpdateNoteApiProjectsProjectIdNotesPatchResponse = UpdateNoteApiProjectsProjectIdNotesPatchResponses[keyof UpdateNoteApiProjectsProjectIdNotesPatchResponses];

export type CreateNoteApiProjectsProjectIdNotesPostData = {
    body: NoteInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/notes';
};

export type CreateNoteApiProjectsProjectIdNotesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNoteApiProjectsProjectIdNotesPostError = CreateNoteApiProjectsProjectIdNotesPostErrors[keyof CreateNoteApiProjectsProjectIdNotesPostErrors];

export type CreateNoteApiProjectsProjectIdNotesPostResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type CreateNoteApiProjectsProjectIdNotesPostResponse = CreateNoteApiProjectsProjectIdNotesPostResponses[keyof CreateNoteApiProjectsProjectIdNotesPostResponses];

export type CreateHighlightApiProjectsProjectIdHighlightsPostData = {
    body: HighlightInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/highlights';
};

export type CreateHighlightApiProjectsProjectIdHighlightsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateHighlightApiProjectsProjectIdHighlightsPostError = CreateHighlightApiProjectsProjectIdHighlightsPostErrors[keyof CreateHighlightApiProjectsProjectIdHighlightsPostErrors];

export type CreateHighlightApiProjectsProjectIdHighlightsPostResponses = {
    /**
     * Successful Response
     */
    200: Highlight;
};

export type CreateHighlightApiProjectsProjectIdHighlightsPostResponse = CreateHighlightApiProjectsProjectIdHighlightsPostResponses[keyof CreateHighlightApiProjectsProjectIdHighlightsPostResponses];

export type QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostData = {
    body: MemoryQueryRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/memory/query';
};

export type QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostError = QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostErrors[keyof QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostErrors];

export type QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostResponses = {
    /**
     * Successful Response
     */
    200: MemoryQueryResponse;
};

export type QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostResponse = QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostResponses[keyof QueryProjectMemoryApiProjectsProjectIdMemoryQueryPostResponses];

export type GetConversationApiProjectsProjectIdConversationGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/conversation';
};

export type GetConversationApiProjectsProjectIdConversationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiProjectsProjectIdConversationGetError = GetConversationApiProjectsProjectIdConversationGetErrors[keyof GetConversationApiProjectsProjectIdConversationGetErrors];

export type GetConversationApiProjectsProjectIdConversationGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type GetConversationApiProjectsProjectIdConversationGetResponse = GetConversationApiProjectsProjectIdConversationGetResponses[keyof GetConversationApiProjectsProjectIdConversationGetResponses];

export type ListExperimentsApiProjectsProjectIdExperimentsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/experiments';
};

export type ListExperimentsApiProjectsProjectIdExperimentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListExperimentsApiProjectsProjectIdExperimentsGetError = ListExperimentsApiProjectsProjectIdExperimentsGetErrors[keyof ListExperimentsApiProjectsProjectIdExperimentsGetErrors];

export type ListExperimentsApiProjectsProjectIdExperimentsGetResponses = {
    /**
     * Response List Experiments Api Projects  Project Id  Experiments Get
     *
     * Successful Response
     */
    200: Array<Experiment>;
};

export type ListExperimentsApiProjectsProjectIdExperimentsGetResponse = ListExperimentsApiProjectsProjectIdExperimentsGetResponses[keyof ListExperimentsApiProjectsProjectIdExperimentsGetResponses];

export type CreateExperimentApiProjectsProjectIdExperimentsPostData = {
    body: ExperimentInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/experiments';
};

export type CreateExperimentApiProjectsProjectIdExperimentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateExperimentApiProjectsProjectIdExperimentsPostError = CreateExperimentApiProjectsProjectIdExperimentsPostErrors[keyof CreateExperimentApiProjectsProjectIdExperimentsPostErrors];

export type CreateExperimentApiProjectsProjectIdExperimentsPostResponses = {
    /**
     * Successful Response
     */
    200: Experiment;
};

export type CreateExperimentApiProjectsProjectIdExperimentsPostResponse = CreateExperimentApiProjectsProjectIdExperimentsPostResponses[keyof CreateExperimentApiProjectsProjectIdExperimentsPostResponses];

export type UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchData = {
    body: ExperimentInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/experiments/{experiment_id}';
};

export type UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchError = UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchErrors[keyof UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchErrors];

export type UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Experiment;
};

export type UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchResponse = UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchResponses[keyof UpdateExperimentApiProjectsProjectIdExperimentsExperimentIdPatchResponses];

export type GetRunSpecApiExperimentsExperimentIdRunSpecGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/run_spec';
};

export type GetRunSpecApiExperimentsExperimentIdRunSpecGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunSpecApiExperimentsExperimentIdRunSpecGetError = GetRunSpecApiExperimentsExperimentIdRunSpecGetErrors[keyof GetRunSpecApiExperimentsExperimentIdRunSpecGetErrors];

export type GetRunSpecApiExperimentsExperimentIdRunSpecGetResponses = {
    /**
     * Successful Response
     */
    200: RunSpecPreview;
};

export type GetRunSpecApiExperimentsExperimentIdRunSpecGetResponse = GetRunSpecApiExperimentsExperimentIdRunSpecGetResponses[keyof GetRunSpecApiExperimentsExperimentIdRunSpecGetResponses];

export type ProposeCellApiExperimentsExperimentIdCellsPostData = {
    body: ProposeCellRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/cells';
};

export type ProposeCellApiExperimentsExperimentIdCellsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProposeCellApiExperimentsExperimentIdCellsPostError = ProposeCellApiExperimentsExperimentIdCellsPostErrors[keyof ProposeCellApiExperimentsExperimentIdCellsPostErrors];

export type ProposeCellApiExperimentsExperimentIdCellsPostResponses = {
    /**
     * Successful Response
     */
    200: Notebook;
};

export type ProposeCellApiExperimentsExperimentIdCellsPostResponse = ProposeCellApiExperimentsExperimentIdCellsPostResponses[keyof ProposeCellApiExperimentsExperimentIdCellsPostResponses];

export type CreateConfirmationApiExperimentsExperimentIdConfirmationPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/confirmation';
};

export type CreateConfirmationApiExperimentsExperimentIdConfirmationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConfirmationApiExperimentsExperimentIdConfirmationPostError = CreateConfirmationApiExperimentsExperimentIdConfirmationPostErrors[keyof CreateConfirmationApiExperimentsExperimentIdConfirmationPostErrors];

export type CreateConfirmationApiExperimentsExperimentIdConfirmationPostResponses = {
    /**
     * Successful Response
     */
    200: ConfirmationToken;
};

export type CreateConfirmationApiExperimentsExperimentIdConfirmationPostResponse = CreateConfirmationApiExperimentsExperimentIdConfirmationPostResponses[keyof CreateConfirmationApiExperimentsExperimentIdConfirmationPostResponses];

export type KernelActionApiExperimentsExperimentIdKernelPostData = {
    body: KernelActionRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/kernel';
};

export type KernelActionApiExperimentsExperimentIdKernelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KernelActionApiExperimentsExperimentIdKernelPostError = KernelActionApiExperimentsExperimentIdKernelPostErrors[keyof KernelActionApiExperimentsExperimentIdKernelPostErrors];

export type KernelActionApiExperimentsExperimentIdKernelPostResponses = {
    /**
     * Successful Response
     */
    200: KernelStatus;
};

export type KernelActionApiExperimentsExperimentIdKernelPostResponse = KernelActionApiExperimentsExperimentIdKernelPostResponses[keyof KernelActionApiExperimentsExperimentIdKernelPostResponses];

export type GetNotebookServerApiExperimentsExperimentIdNotebookServerGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/notebook_server';
};

export type GetNotebookServerApiExperimentsExperimentIdNotebookServerGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNotebookServerApiExperimentsExperimentIdNotebookServerGetError = GetNotebookServerApiExperimentsExperimentIdNotebookServerGetErrors[keyof GetNotebookServerApiExperimentsExperimentIdNotebookServerGetErrors];

export type GetNotebookServerApiExperimentsExperimentIdNotebookServerGetResponses = {
    /**
     * Successful Response
     */
    200: NotebookServerStatus;
};

export type GetNotebookServerApiExperimentsExperimentIdNotebookServerGetResponse = GetNotebookServerApiExperimentsExperimentIdNotebookServerGetResponses[keyof GetNotebookServerApiExperimentsExperimentIdNotebookServerGetResponses];

export type NotebookServerActionApiExperimentsExperimentIdNotebookServerPostData = {
    body: NotebookServerAction;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/notebook_server';
};

export type NotebookServerActionApiExperimentsExperimentIdNotebookServerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotebookServerActionApiExperimentsExperimentIdNotebookServerPostError = NotebookServerActionApiExperimentsExperimentIdNotebookServerPostErrors[keyof NotebookServerActionApiExperimentsExperimentIdNotebookServerPostErrors];

export type NotebookServerActionApiExperimentsExperimentIdNotebookServerPostResponses = {
    /**
     * Successful Response
     */
    200: NotebookServerStatus;
};

export type NotebookServerActionApiExperimentsExperimentIdNotebookServerPostResponse = NotebookServerActionApiExperimentsExperimentIdNotebookServerPostResponses[keyof NotebookServerActionApiExperimentsExperimentIdNotebookServerPostResponses];

export type RunAllApiExperimentsExperimentIdRunAllPostData = {
    body: RunAllRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/run_all';
};

export type RunAllApiExperimentsExperimentIdRunAllPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunAllApiExperimentsExperimentIdRunAllPostError = RunAllApiExperimentsExperimentIdRunAllPostErrors[keyof RunAllApiExperimentsExperimentIdRunAllPostErrors];

export type RunAllApiExperimentsExperimentIdRunAllPostResponses = {
    /**
     * Successful Response
     */
    200: RunAllResponse;
};

export type RunAllApiExperimentsExperimentIdRunAllPostResponse = RunAllApiExperimentsExperimentIdRunAllPostResponses[keyof RunAllApiExperimentsExperimentIdRunAllPostResponses];

export type GetRunApiRunsRunIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}';
};

export type GetRunApiRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunApiRunsRunIdGetError = GetRunApiRunsRunIdGetErrors[keyof GetRunApiRunsRunIdGetErrors];

export type GetRunApiRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunDetail;
};

export type GetRunApiRunsRunIdGetResponse = GetRunApiRunsRunIdGetResponses[keyof GetRunApiRunsRunIdGetResponses];

export type CreateMetricApiExperimentsExperimentIdMetricsPostData = {
    body: MetricInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/api/experiments/{experiment_id}/metrics';
};

export type CreateMetricApiExperimentsExperimentIdMetricsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMetricApiExperimentsExperimentIdMetricsPostError = CreateMetricApiExperimentsExperimentIdMetricsPostErrors[keyof CreateMetricApiExperimentsExperimentIdMetricsPostErrors];

export type CreateMetricApiExperimentsExperimentIdMetricsPostResponses = {
    /**
     * Successful Response
     */
    200: ExperimentMetric;
};

export type CreateMetricApiExperimentsExperimentIdMetricsPostResponse = CreateMetricApiExperimentsExperimentIdMetricsPostResponses[keyof CreateMetricApiExperimentsExperimentIdMetricsPostResponses];

export type TranscribeAudioApiVoiceTranscribePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string;
    };
    url: '/api/voice/transcribe';
};

export type TranscribeAudioApiVoiceTranscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeAudioApiVoiceTranscribePostError = TranscribeAudioApiVoiceTranscribePostErrors[keyof TranscribeAudioApiVoiceTranscribePostErrors];

export type TranscribeAudioApiVoiceTranscribePostResponses = {
    /**
     * Successful Response
     */
    200: Transcript;
};

export type TranscribeAudioApiVoiceTranscribePostResponse = TranscribeAudioApiVoiceTranscribePostResponses[keyof TranscribeAudioApiVoiceTranscribePostResponses];

export type SynthesizeSpeechApiVoiceSynthesizePostData = {
    body: SynthesizeRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/voice/synthesize';
};

export type SynthesizeSpeechApiVoiceSynthesizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SynthesizeSpeechApiVoiceSynthesizePostError = SynthesizeSpeechApiVoiceSynthesizePostErrors[keyof SynthesizeSpeechApiVoiceSynthesizePostErrors];

export type SynthesizeSpeechApiVoiceSynthesizePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListProjectPapersApiProjectsProjectIdPapersGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/papers';
};

export type ListProjectPapersApiProjectsProjectIdPapersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectPapersApiProjectsProjectIdPapersGetError = ListProjectPapersApiProjectsProjectIdPapersGetErrors[keyof ListProjectPapersApiProjectsProjectIdPapersGetErrors];

export type ListProjectPapersApiProjectsProjectIdPapersGetResponses = {
    /**
     * Response List Project Papers Api Projects  Project Id  Papers Get
     *
     * Successful Response
     */
    200: Array<LibraryEntry>;
};

export type ListProjectPapersApiProjectsProjectIdPapersGetResponse = ListProjectPapersApiProjectsProjectIdPapersGetResponses[keyof ListProjectPapersApiProjectsProjectIdPapersGetResponses];

export type AddPaperApiProjectsProjectIdPapersPostData = {
    body: PaperInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/papers';
};

export type AddPaperApiProjectsProjectIdPapersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPaperApiProjectsProjectIdPapersPostError = AddPaperApiProjectsProjectIdPapersPostErrors[keyof AddPaperApiProjectsProjectIdPapersPostErrors];

export type AddPaperApiProjectsProjectIdPapersPostResponses = {
    /**
     * Successful Response
     */
    200: Paper;
};

export type AddPaperApiProjectsProjectIdPapersPostResponse = AddPaperApiProjectsProjectIdPapersPostResponses[keyof AddPaperApiProjectsProjectIdPapersPostResponses];

export type GetPaperApiPapersPaperIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Paper Id
         */
        paper_id: string;
    };
    query?: {
        /**
         * Include
         */
        include?: string;
    };
    url: '/api/papers/{paper_id}';
};

export type GetPaperApiPapersPaperIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaperApiPapersPaperIdGetError = GetPaperApiPapersPaperIdGetErrors[keyof GetPaperApiPapersPaperIdGetErrors];

export type GetPaperApiPapersPaperIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaperDetail;
};

export type GetPaperApiPapersPaperIdGetResponse = GetPaperApiPapersPaperIdGetResponses[keyof GetPaperApiPapersPaperIdGetResponses];

export type GetPaperPdfApiPapersPaperIdPdfGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Paper Id
         */
        paper_id: string;
    };
    query?: never;
    url: '/api/papers/{paper_id}/pdf';
};

export type GetPaperPdfApiPapersPaperIdPdfGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaperPdfApiPapersPaperIdPdfGetError = GetPaperPdfApiPapersPaperIdPdfGetErrors[keyof GetPaperPdfApiPapersPaperIdPdfGetErrors];

export type GetPaperPdfApiPapersPaperIdPdfGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Paper Id
         */
        paper_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/papers/{paper_id}/reprocess';
};

export type ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostError = ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostErrors[keyof ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostErrors];

export type ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostResponses = {
    /**
     * Successful Response
     */
    200: Paper;
};

export type ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostResponse = ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostResponses[keyof ReprocessPaperApiProjectsProjectIdPapersPaperIdReprocessPostResponses];

export type PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchData = {
    body: PatchProjectPaperRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Paper Id
         */
        paper_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/papers/{paper_id}';
};

export type PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchError = PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchErrors[keyof PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchErrors];

export type PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectPaperResponse;
};

export type PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchResponse = PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchResponses[keyof PatchProjectPaperApiProjectsProjectIdPapersPaperIdPatchResponses];

export type GetAnchorApiAnchorsAnchorIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Anchor Id
         */
        anchor_id: string;
    };
    query?: never;
    url: '/api/anchors/{anchor_id}';
};

export type GetAnchorApiAnchorsAnchorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnchorApiAnchorsAnchorIdGetError = GetAnchorApiAnchorsAnchorIdGetErrors[keyof GetAnchorApiAnchorsAnchorIdGetErrors];

export type GetAnchorApiAnchorsAnchorIdGetResponses = {
    /**
     * Successful Response
     */
    200: QuoteAnchor;
};

export type GetAnchorApiAnchorsAnchorIdGetResponse = GetAnchorApiAnchorsAnchorIdGetResponses[keyof GetAnchorApiAnchorsAnchorIdGetResponses];

export type PostSearchApiSearchPostData = {
    body: SearchRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/search';
};

export type PostSearchApiSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostSearchApiSearchPostError = PostSearchApiSearchPostErrors[keyof PostSearchApiSearchPostErrors];

export type PostSearchApiSearchPostResponses = {
    /**
     * Successful Response
     */
    200: ResultSet;
};

export type PostSearchApiSearchPostResponse = PostSearchApiSearchPostResponses[keyof PostSearchApiSearchPostResponses];

export type GetResultApiResultsResultIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Result Id
         */
        result_id: string;
    };
    query?: never;
    url: '/api/results/{result_id}';
};

export type GetResultApiResultsResultIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResultApiResultsResultIdGetError = GetResultApiResultsResultIdGetErrors[keyof GetResultApiResultsResultIdGetErrors];

export type GetResultApiResultsResultIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResultSet;
};

export type GetResultApiResultsResultIdGetResponse = GetResultApiResultsResultIdGetResponses[keyof GetResultApiResultsResultIdGetResponses];

export type ListMatricesApiProjectsProjectIdMatrixGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/matrix';
};

export type ListMatricesApiProjectsProjectIdMatrixGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMatricesApiProjectsProjectIdMatrixGetError = ListMatricesApiProjectsProjectIdMatrixGetErrors[keyof ListMatricesApiProjectsProjectIdMatrixGetErrors];

export type ListMatricesApiProjectsProjectIdMatrixGetResponses = {
    /**
     * Response List Matrices Api Projects  Project Id  Matrix Get
     *
     * Successful Response
     */
    200: Array<Matrix>;
};

export type ListMatricesApiProjectsProjectIdMatrixGetResponse = ListMatricesApiProjectsProjectIdMatrixGetResponses[keyof ListMatricesApiProjectsProjectIdMatrixGetResponses];

export type CreateMatrixApiProjectsProjectIdMatrixPostData = {
    body: MatrixUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/matrix';
};

export type CreateMatrixApiProjectsProjectIdMatrixPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMatrixApiProjectsProjectIdMatrixPostError = CreateMatrixApiProjectsProjectIdMatrixPostErrors[keyof CreateMatrixApiProjectsProjectIdMatrixPostErrors];

export type CreateMatrixApiProjectsProjectIdMatrixPostResponses = {
    /**
     * Successful Response
     */
    200: Matrix;
};

export type CreateMatrixApiProjectsProjectIdMatrixPostResponse = CreateMatrixApiProjectsProjectIdMatrixPostResponses[keyof CreateMatrixApiProjectsProjectIdMatrixPostResponses];

export type GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Matrix Id
         */
        matrix_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/matrix/{matrix_id}';
};

export type GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetError = GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetErrors[keyof GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetErrors];

export type GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetResponses = {
    /**
     * Successful Response
     */
    200: MatrixView;
};

export type GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetResponse = GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetResponses[keyof GetMatrixViewApiProjectsProjectIdMatrixMatrixIdGetResponses];

export type PutMatrixApiProjectsProjectIdMatrixMatrixIdPutData = {
    body: MatrixUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Matrix Id
         */
        matrix_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/matrix/{matrix_id}';
};

export type PutMatrixApiProjectsProjectIdMatrixMatrixIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutMatrixApiProjectsProjectIdMatrixMatrixIdPutError = PutMatrixApiProjectsProjectIdMatrixMatrixIdPutErrors[keyof PutMatrixApiProjectsProjectIdMatrixMatrixIdPutErrors];

export type PutMatrixApiProjectsProjectIdMatrixMatrixIdPutResponses = {
    /**
     * Successful Response
     */
    200: Matrix;
};

export type PutMatrixApiProjectsProjectIdMatrixMatrixIdPutResponse = PutMatrixApiProjectsProjectIdMatrixMatrixIdPutResponses[keyof PutMatrixApiProjectsProjectIdMatrixMatrixIdPutResponses];

export type UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchData = {
    body: UpdateCellRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Matrix Id
         */
        matrix_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/matrix/{matrix_id}/cells';
};

export type UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchError = UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchErrors[keyof UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchErrors];

export type UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchResponses = {
    /**
     * Successful Response
     */
    200: MatrixCell;
};

export type UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchResponse = UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchResponses[keyof UpdateCellApiProjectsProjectIdMatrixMatrixIdCellsPatchResponses];

export type GetProjectGraphApiProjectsProjectIdGraphGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Types
         */
        types?: string;
    };
    url: '/api/projects/{project_id}/graph';
};

export type GetProjectGraphApiProjectsProjectIdGraphGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectGraphApiProjectsProjectIdGraphGetError = GetProjectGraphApiProjectsProjectIdGraphGetErrors[keyof GetProjectGraphApiProjectsProjectIdGraphGetErrors];

export type GetProjectGraphApiProjectsProjectIdGraphGetResponses = {
    /**
     * Successful Response
     */
    200: Graph;
};

export type GetProjectGraphApiProjectsProjectIdGraphGetResponse = GetProjectGraphApiProjectsProjectIdGraphGetResponses[keyof GetProjectGraphApiProjectsProjectIdGraphGetResponses];

export type ListDocumentsApiProjectsProjectIdDocumentsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/documents';
};

export type ListDocumentsApiProjectsProjectIdDocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsApiProjectsProjectIdDocumentsGetError = ListDocumentsApiProjectsProjectIdDocumentsGetErrors[keyof ListDocumentsApiProjectsProjectIdDocumentsGetErrors];

export type ListDocumentsApiProjectsProjectIdDocumentsGetResponses = {
    /**
     * Response List Documents Api Projects  Project Id  Documents Get
     *
     * Successful Response
     */
    200: Array<Document>;
};

export type ListDocumentsApiProjectsProjectIdDocumentsGetResponse = ListDocumentsApiProjectsProjectIdDocumentsGetResponses[keyof ListDocumentsApiProjectsProjectIdDocumentsGetResponses];

export type CreateDocumentApiProjectsProjectIdDocumentsPostData = {
    body: SaveDocumentRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/documents';
};

export type CreateDocumentApiProjectsProjectIdDocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDocumentApiProjectsProjectIdDocumentsPostError = CreateDocumentApiProjectsProjectIdDocumentsPostErrors[keyof CreateDocumentApiProjectsProjectIdDocumentsPostErrors];

export type CreateDocumentApiProjectsProjectIdDocumentsPostResponses = {
    /**
     * Response Create Document Api Projects  Project Id  Documents Post
     *
     * Successful Response
     */
    200: Document | CompileResult;
};

export type CreateDocumentApiProjectsProjectIdDocumentsPostResponse = CreateDocumentApiProjectsProjectIdDocumentsPostResponses[keyof CreateDocumentApiProjectsProjectIdDocumentsPostResponses];

export type GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/documents/{document_id}';
};

export type GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetError = GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetErrors[keyof GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetErrors];

export type GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetResponses = {
    /**
     * Successful Response
     */
    200: Document;
};

export type GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetResponse = GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetResponses[keyof GetDocumentApiProjectsProjectIdDocumentsDocumentIdGetResponses];

export type UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutData = {
    body: SaveDocumentRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/documents/{document_id}';
};

export type UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutError = UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutErrors[keyof UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutErrors];

export type UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutResponses = {
    /**
     * Response Update Document Api Projects  Project Id  Documents  Document Id  Put
     *
     * Successful Response
     */
    200: Document | CompileResult;
};

export type UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutResponse = UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutResponses[keyof UpdateDocumentApiProjectsProjectIdDocumentsDocumentIdPutResponses];

export type GetDocumentPdfApiProjectsProjectIdDocumentsDocumentIdPdfGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/documents/{document_id}/pdf';
};

export type GetDocumentPdfApiProjectsProjectIdDocumentsDocumentIdPdfGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentPdfApiProjectsProjectIdDocumentsDocumentIdPdfGetError = GetDocumentPdfApiProjectsProjectIdDocumentsDocumentIdPdfGetErrors[keyof GetDocumentPdfApiProjectsProjectIdDocumentsDocumentIdPdfGetErrors];

export type GetDocumentPdfApiProjectsProjectIdDocumentsDocumentIdPdfGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostData = {
    body: BodyInsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPost;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/documents/{document_id}/assets';
};

export type InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostError = InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostErrors[keyof InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostErrors];

export type InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostResponses = {
    /**
     * Successful Response
     */
    200: AssetInserted;
};

export type InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostResponse = InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostResponses[keyof InsertAssetApiProjectsProjectIdDocumentsDocumentIdAssetsPostResponses];

export type CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/documents/{document_id}/check_citations';
};

export type CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostError = CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostErrors[keyof CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostErrors];

export type CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostResponses = {
    /**
     * Successful Response
     */
    200: CheckCitationsResponse;
};

export type CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostResponse = CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostResponses[keyof CheckCitationsApiProjectsProjectIdDocumentsDocumentIdCheckCitationsPostResponses];

export type ListReferencesApiProjectsProjectIdReferencesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Prefix
         */
        prefix?: string;
    };
    url: '/api/projects/{project_id}/references';
};

export type ListReferencesApiProjectsProjectIdReferencesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListReferencesApiProjectsProjectIdReferencesGetError = ListReferencesApiProjectsProjectIdReferencesGetErrors[keyof ListReferencesApiProjectsProjectIdReferencesGetErrors];

export type ListReferencesApiProjectsProjectIdReferencesGetResponses = {
    /**
     * Response List References Api Projects  Project Id  References Get
     *
     * Successful Response
     */
    200: Array<Reference>;
};

export type ListReferencesApiProjectsProjectIdReferencesGetResponse = ListReferencesApiProjectsProjectIdReferencesGetResponses[keyof ListReferencesApiProjectsProjectIdReferencesGetResponses];

export type ExportBibtexApiProjectsProjectIdBibtexGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/bibtex';
};

export type ExportBibtexApiProjectsProjectIdBibtexGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportBibtexApiProjectsProjectIdBibtexGetError = ExportBibtexApiProjectsProjectIdBibtexGetErrors[keyof ExportBibtexApiProjectsProjectIdBibtexGetErrors];

export type ExportBibtexApiProjectsProjectIdBibtexGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type ExportBibtexApiProjectsProjectIdBibtexGetResponse = ExportBibtexApiProjectsProjectIdBibtexGetResponses[keyof ExportBibtexApiProjectsProjectIdBibtexGetResponses];

export type GetInterestProfileApiProjectsProjectIdInterestProfileGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/interest-profile';
};

export type GetInterestProfileApiProjectsProjectIdInterestProfileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterestProfileApiProjectsProjectIdInterestProfileGetError = GetInterestProfileApiProjectsProjectIdInterestProfileGetErrors[keyof GetInterestProfileApiProjectsProjectIdInterestProfileGetErrors];

export type GetInterestProfileApiProjectsProjectIdInterestProfileGetResponses = {
    /**
     * Successful Response
     */
    200: InterestProfile;
};

export type GetInterestProfileApiProjectsProjectIdInterestProfileGetResponse = GetInterestProfileApiProjectsProjectIdInterestProfileGetResponses[keyof GetInterestProfileApiProjectsProjectIdInterestProfileGetResponses];

export type PutInterestProfileApiProjectsProjectIdInterestProfilePutData = {
    body: InterestProfile;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/interest-profile';
};

export type PutInterestProfileApiProjectsProjectIdInterestProfilePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutInterestProfileApiProjectsProjectIdInterestProfilePutError = PutInterestProfileApiProjectsProjectIdInterestProfilePutErrors[keyof PutInterestProfileApiProjectsProjectIdInterestProfilePutErrors];

export type PutInterestProfileApiProjectsProjectIdInterestProfilePutResponses = {
    /**
     * Successful Response
     */
    200: InterestProfile;
};

export type PutInterestProfileApiProjectsProjectIdInterestProfilePutResponse = PutInterestProfileApiProjectsProjectIdInterestProfilePutResponses[keyof PutInterestProfileApiProjectsProjectIdInterestProfilePutResponses];

export type ListFeedApiProjectsProjectIdFeedGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/feed';
};

export type ListFeedApiProjectsProjectIdFeedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFeedApiProjectsProjectIdFeedGetError = ListFeedApiProjectsProjectIdFeedGetErrors[keyof ListFeedApiProjectsProjectIdFeedGetErrors];

export type ListFeedApiProjectsProjectIdFeedGetResponses = {
    /**
     * Response List Feed Api Projects  Project Id  Feed Get
     *
     * Successful Response
     */
    200: Array<FeedItem>;
};

export type ListFeedApiProjectsProjectIdFeedGetResponse = ListFeedApiProjectsProjectIdFeedGetResponses[keyof ListFeedApiProjectsProjectIdFeedGetResponses];

export type ActOnFeedItemApiProjectsProjectIdFeedPostData = {
    body: FeedActionRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/feed';
};

export type ActOnFeedItemApiProjectsProjectIdFeedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActOnFeedItemApiProjectsProjectIdFeedPostError = ActOnFeedItemApiProjectsProjectIdFeedPostErrors[keyof ActOnFeedItemApiProjectsProjectIdFeedPostErrors];

export type ActOnFeedItemApiProjectsProjectIdFeedPostResponses = {
    /**
     * Response Act On Feed Item Api Projects  Project Id  Feed Post
     *
     * Successful Response
     */
    200: Array<FeedItem>;
};

export type ActOnFeedItemApiProjectsProjectIdFeedPostResponse = ActOnFeedItemApiProjectsProjectIdFeedPostResponses[keyof ActOnFeedItemApiProjectsProjectIdFeedPostResponses];
