// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Capabilities
     */
    capabilities: {
        [key: string]: 'pending' | 'ready' | 'failed';
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetHealthApiHealthGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthApiHealthGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHealthApiHealthGetError = GetHealthApiHealthGetErrors[keyof GetHealthApiHealthGetErrors];

export type GetHealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthApiHealthGetResponse = GetHealthApiHealthGetResponses[keyof GetHealthApiHealthGetResponses];
