// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CreateProjectRequest
 */
export type CreateProjectRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Focus Seed
     */
    focus_seed?: string | null;
};

/**
 * DiscoverModelsRequest
 */
export type DiscoverModelsRequest = {
    /**
     * Provider
     */
    provider: 'ollama' | 'vllm';
    /**
     * Base Url
     */
    base_url: string;
};

/**
 * DiscoverModelsResponse
 */
export type DiscoverModelsResponse = {
    /**
     * Models
     */
    models: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Capabilities
     */
    capabilities: {
        [key: string]: 'pending' | 'ready' | 'failed';
    };
};

/**
 * ModelSettings
 */
export type ModelSettings = {
    /**
     * Providers
     */
    providers: {
        [key: string]: ProviderInfo;
    };
    /**
     * Primary Model
     */
    primary_model?: string | null;
    /**
     * Auxiliary Model
     */
    auxiliary_model?: string | null;
    /**
     * Onboarding Completed At
     */
    onboarding_completed_at?: string | null;
};

/**
 * Note
 *
 * The `notes` row (Schema.md), returned by every notes endpoint.
 */
export type Note = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Body
     */
    body: string;
    /**
     * Frontmatter
     */
    frontmatter: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * NoteInput
 *
 * What a caller submits to create or update a note.
 *
 * `frontmatter_id` is absent to create (Vault Writer assigns one) and
 * present to update — the id carried in the note's own YAML frontmatter,
 * never the file path (D4).
 */
export type NoteInput = {
    /**
     * Frontmatter Id
     */
    frontmatter_id?: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
};

/**
 * PaperSummary
 */
export type PaperSummary = {
    /**
     * Canonical Id
     */
    canonical_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Abstract
     */
    abstract?: string | null;
    /**
     * Authors
     */
    authors?: Array<string>;
    /**
     * Year
     */
    year?: number | null;
    /**
     * Venue
     */
    venue?: string | null;
    /**
     * Citation Count
     */
    citation_count?: number | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Pdf Url
     */
    pdf_url?: string | null;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Focus Seed
     */
    focus_seed: string | null;
    /**
     * Last Opened At
     */
    last_opened_at: string | null;
};

/**
 * ProviderCredentials
 *
 * What the user submits to save and validate one provider.
 */
export type ProviderCredentials = {
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Tier
     */
    tier?: 'primary' | 'auxiliary';
};

/**
 * ProviderInfo
 *
 * What is ever read back — never ciphertext, nonce, or plaintext key.
 */
export type ProviderInfo = {
    /**
     * Last4
     */
    last4?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Validated At
     */
    validated_at?: string | null;
};

/**
 * ResultSet
 */
export type ResultSet = {
    /**
     * Result Id
     */
    result_id: string;
    /**
     * Query
     */
    query: string;
    /**
     * Results
     */
    results: Array<PaperSummary>;
    /**
     * Sources Failed
     */
    sources_failed?: Array<string>;
};

/**
 * SaveProviderRequest
 */
export type SaveProviderRequest = {
    /**
     * Provider
     */
    provider: 'google' | 'groq' | 'openai' | 'anthropic' | 'openrouter' | 'deepseek' | 'custom' | 'ollama' | 'vllm';
    credentials: ProviderCredentials;
};

/**
 * SearchFilters
 */
export type SearchFilters = {
    /**
     * Year Min
     */
    year_min?: number | null;
    /**
     * Year Max
     */
    year_max?: number | null;
    /**
     * Venue
     */
    venue?: string | null;
    /**
     * Has Code
     */
    has_code?: boolean | null;
    /**
     * Author
     */
    author?: string | null;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
    filters?: SearchFilters | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VaultPathRequest
 */
export type VaultPathRequest = {
    /**
     * Path
     */
    path: string;
};

export type GetHealthApiHealthGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthApiHealthGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHealthApiHealthGetError = GetHealthApiHealthGetErrors[keyof GetHealthApiHealthGetErrors];

export type GetHealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthApiHealthGetResponse = GetHealthApiHealthGetResponses[keyof GetHealthApiHealthGetResponses];

export type GetModelsApiSettingsModelsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/models';
};

export type GetModelsApiSettingsModelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelsApiSettingsModelsGetError = GetModelsApiSettingsModelsGetErrors[keyof GetModelsApiSettingsModelsGetErrors];

export type GetModelsApiSettingsModelsGetResponses = {
    /**
     * Successful Response
     */
    200: ModelSettings;
};

export type GetModelsApiSettingsModelsGetResponse = GetModelsApiSettingsModelsGetResponses[keyof GetModelsApiSettingsModelsGetResponses];

export type PutModelsApiSettingsModelsPutData = {
    body: SaveProviderRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/models';
};

export type PutModelsApiSettingsModelsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutModelsApiSettingsModelsPutError = PutModelsApiSettingsModelsPutErrors[keyof PutModelsApiSettingsModelsPutErrors];

export type PutModelsApiSettingsModelsPutResponses = {
    /**
     * Successful Response
     */
    200: ModelSettings;
};

export type PutModelsApiSettingsModelsPutResponse = PutModelsApiSettingsModelsPutResponses[keyof PutModelsApiSettingsModelsPutResponses];

export type DiscoverModelsApiSettingsModelsDiscoverPostData = {
    body: DiscoverModelsRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/models/discover';
};

export type DiscoverModelsApiSettingsModelsDiscoverPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DiscoverModelsApiSettingsModelsDiscoverPostError = DiscoverModelsApiSettingsModelsDiscoverPostErrors[keyof DiscoverModelsApiSettingsModelsDiscoverPostErrors];

export type DiscoverModelsApiSettingsModelsDiscoverPostResponses = {
    /**
     * Successful Response
     */
    200: DiscoverModelsResponse;
};

export type DiscoverModelsApiSettingsModelsDiscoverPostResponse = DiscoverModelsApiSettingsModelsDiscoverPostResponses[keyof DiscoverModelsApiSettingsModelsDiscoverPostResponses];

export type PutVaultPathApiSettingsVaultPathPutData = {
    body: VaultPathRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/vault-path';
};

export type PutVaultPathApiSettingsVaultPathPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutVaultPathApiSettingsVaultPathPutError = PutVaultPathApiSettingsVaultPathPutErrors[keyof PutVaultPathApiSettingsVaultPathPutErrors];

export type PutVaultPathApiSettingsVaultPathPutResponses = {
    /**
     * Response Put Vault Path Api Settings Vault Path Put
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PutVaultPathApiSettingsVaultPathPutResponse = PutVaultPathApiSettingsVaultPathPutResponses[keyof PutVaultPathApiSettingsVaultPathPutResponses];

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/settings/onboarding-complete';
};

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutError = PutOnboardingCompleteApiSettingsOnboardingCompletePutErrors[keyof PutOnboardingCompleteApiSettingsOnboardingCompletePutErrors];

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutResponses = {
    /**
     * Successful Response
     */
    200: ModelSettings;
};

export type PutOnboardingCompleteApiSettingsOnboardingCompletePutResponse = PutOnboardingCompleteApiSettingsOnboardingCompletePutResponses[keyof PutOnboardingCompleteApiSettingsOnboardingCompletePutResponses];

export type ListProjectsApiProjectsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type ListProjectsApiProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsApiProjectsGetError = ListProjectsApiProjectsGetErrors[keyof ListProjectsApiProjectsGetErrors];

export type ListProjectsApiProjectsGetResponses = {
    /**
     * Response List Projects Api Projects Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type ListProjectsApiProjectsGetResponse = ListProjectsApiProjectsGetResponses[keyof ListProjectsApiProjectsGetResponses];

export type CreateProjectApiProjectsPostData = {
    body: CreateProjectRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type CreateProjectApiProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiProjectsPostError = CreateProjectApiProjectsPostErrors[keyof CreateProjectApiProjectsPostErrors];

export type CreateProjectApiProjectsPostResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type CreateProjectApiProjectsPostResponse = CreateProjectApiProjectsPostResponses[keyof CreateProjectApiProjectsPostResponses];

export type GetProjectApiProjectsProjectIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type GetProjectApiProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiProjectsProjectIdGetError = GetProjectApiProjectsProjectIdGetErrors[keyof GetProjectApiProjectsProjectIdGetErrors];

export type GetProjectApiProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectApiProjectsProjectIdGetResponse = GetProjectApiProjectsProjectIdGetResponses[keyof GetProjectApiProjectsProjectIdGetResponses];

export type ListNotesApiProjectsProjectIdNotesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/notes';
};

export type ListNotesApiProjectsProjectIdNotesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListNotesApiProjectsProjectIdNotesGetError = ListNotesApiProjectsProjectIdNotesGetErrors[keyof ListNotesApiProjectsProjectIdNotesGetErrors];

export type ListNotesApiProjectsProjectIdNotesGetResponses = {
    /**
     * Response List Notes Api Projects  Project Id  Notes Get
     *
     * Successful Response
     */
    200: Array<Note>;
};

export type ListNotesApiProjectsProjectIdNotesGetResponse = ListNotesApiProjectsProjectIdNotesGetResponses[keyof ListNotesApiProjectsProjectIdNotesGetResponses];

export type UpdateNoteApiProjectsProjectIdNotesPatchData = {
    body: NoteInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/notes';
};

export type UpdateNoteApiProjectsProjectIdNotesPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNoteApiProjectsProjectIdNotesPatchError = UpdateNoteApiProjectsProjectIdNotesPatchErrors[keyof UpdateNoteApiProjectsProjectIdNotesPatchErrors];

export type UpdateNoteApiProjectsProjectIdNotesPatchResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type UpdateNoteApiProjectsProjectIdNotesPatchResponse = UpdateNoteApiProjectsProjectIdNotesPatchResponses[keyof UpdateNoteApiProjectsProjectIdNotesPatchResponses];

export type CreateNoteApiProjectsProjectIdNotesPostData = {
    body: NoteInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/notes';
};

export type CreateNoteApiProjectsProjectIdNotesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNoteApiProjectsProjectIdNotesPostError = CreateNoteApiProjectsProjectIdNotesPostErrors[keyof CreateNoteApiProjectsProjectIdNotesPostErrors];

export type CreateNoteApiProjectsProjectIdNotesPostResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type CreateNoteApiProjectsProjectIdNotesPostResponse = CreateNoteApiProjectsProjectIdNotesPostResponses[keyof CreateNoteApiProjectsProjectIdNotesPostResponses];

export type PostSearchApiSearchPostData = {
    body: SearchRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/search';
};

export type PostSearchApiSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostSearchApiSearchPostError = PostSearchApiSearchPostErrors[keyof PostSearchApiSearchPostErrors];

export type PostSearchApiSearchPostResponses = {
    /**
     * Successful Response
     */
    200: ResultSet;
};

export type PostSearchApiSearchPostResponse = PostSearchApiSearchPostResponses[keyof PostSearchApiSearchPostResponses];

export type GetResultApiResultsResultIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Result Id
         */
        result_id: string;
    };
    query?: never;
    url: '/api/results/{result_id}';
};

export type GetResultApiResultsResultIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResultApiResultsResultIdGetError = GetResultApiResultsResultIdGetErrors[keyof GetResultApiResultsResultIdGetErrors];

export type GetResultApiResultsResultIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResultSet;
};

export type GetResultApiResultsResultIdGetResponse = GetResultApiResultsResultIdGetResponses[keyof GetResultApiResultsResultIdGetResponses];
