"""Process-level configuration, read once from the environment.

Not a domain module (see MODULES.md) — this is the one place infra values
(DB connection, the per-launch bearer token) are read from the environment,
so no other module hardcodes a port, URL or credential (Rules.md).

`BEARER_TOKEN` is regenerated by the desktop shell on every real launch
(D2) — it is never meant to be a fixed secret. `.env` exists only for
running the sidecar standalone (no Electron) during development; see
`.env.example`. A provider API key (e.g. Groq) is never read from here —
D13 requires it go through Settings Store's validated, encrypted-storage
path (`scripts/configure_provider.py` drives that path from `.env` for
convenience; it does not bypass it).

`FIRECRAWL_API_KEY` is the one flagged exception (D21 amendment): D13's
Settings-Store-encrypted path covers *LLM provider* credentials only.
Firecrawl is an infra key Search Federation calls directly, same category
as the DB DSN above — so it is read here, not through Settings Store. It
is optional: a missing key is a valid degrade-to-fallback state for search
(Rules.md "Partial source failure degrades, it does not fail"), never a
startup failure.
"""

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class Config(BaseSettings):
    model_config = SettingsConfigDict(env_file=Path(__file__).parent / ".env", env_file_encoding="utf-8", extra="ignore")

    bearer_token: str
    postgres_user: str = "researchos"
    postgres_password: str = "researchos"
    postgres_db: str = "researchos"
    postgres_port: int = 5433
    firecrawl_api_key: str | None = None

    @property
    def database_url(self) -> str:
        """The app's runtime connection string — asyncpg, per TRD §1.4."""
        return self._url("asyncpg")

    @property
    def sync_database_url(self) -> str:
        """Alembic's own migration runner needs a sync driver; psycopg (v3)
        is already a transitive dependency via saq[postgres], so it costs no
        extra dependency to reuse it here instead of adding psycopg2."""
        return self._url("psycopg")

    @property
    def libpq_dsn(self) -> str:
        """Plain libpq-style DSN (no SQLAlchemy driver suffix) for SAQ's
        PostgresQueue, which opens its own psycopg pool directly."""
        return (
            f"postgresql://{self.postgres_user}:{self.postgres_password}"
            f"@127.0.0.1:{self.postgres_port}/{self.postgres_db}"
        )

    def _url(self, driver: str) -> str:
        return (
            f"postgresql+{driver}://{self.postgres_user}:{self.postgres_password}"
            f"@127.0.0.1:{self.postgres_port}/{self.postgres_db}"
        )


@lru_cache
def get_config() -> Config:
    return Config()
