// The package entry point. Re-exports the generated SDK functions/types
// (src/client, regenerated by `npm run generate`) plus the one hand-written
// piece: wiring the client singleton's baseUrl/token from the Electron
// bridge, since that's a runtime value the generator cannot know.

export * from "./client/index";
export { client } from "./client/client.gen";
